rmn_arch_0/chat/urls.py
from django.urls import path
from .views import (
    ChatView,
    ChatContentAJAXView,
)

app_name = 'chat'

urlpatterns = [
    path('', ChatView.as_view(), name='messages'),
    path('chat-content/<str:room_name>/', ChatContentAJAXView.as_view(), name='chat_content'),
]

rmn_arch_0/core/urls.py
from django.urls import path
from .views import terms_and_conditions

app_name = 'core'

urlpatterns = [
    path('terms-and-conditions/', terms_and_conditions, name='terms_and_conditions'),
]

rmn_arch_0/posts/urls.py
from django.urls import path
from .views import (
    HomeView,
    RankView,
    FollowView,
    PostCreateModalView,
    PostDetailModalView,
    PostDetailView,
    PostCommentAJAXView,
    PostReportAJAXView,
    PostRateAJAXView,
    UserPostsView,
)

app_name = 'posts'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('rank/', RankView.as_view(), name='rank'),
    path('follow/', FollowView.as_view(), name='follow'),
    path('posts/create/m/', PostCreateModalView.as_view(), name='post_create_modal'),
    path('posts/<uuid:uuid>/m/', PostDetailModalView.as_view(), name='post_detail_modal'),
    path('posts/<uuid:uuid>/', PostDetailView.as_view(), name='post_detail'),
    path('posts/<uuid:uuid>/comment/', PostCommentAJAXView.as_view(), name='post_comment'),
    path('posts/<uuid:uuid>/report/', PostReportAJAXView.as_view(), name='post_report'),
    path('posts/rate/', PostRateAJAXView.as_view(), name='rate'),
    path('users/<str:username>/posts/', UserPostsView.as_view(), name='user_posts'),
]

rmn_arch_0/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.views.defaults import page_not_found
from django.urls import path, include


urlpatterns = [
    path('', include('rmn_arch_0.core.urls')),
    path('', include('rmn_arch_0.posts.urls')),
    path('messages/', include('rmn_arch_0.chat.urls')),
    path('users/', include('rmn_arch_0.users.urls')),
    # block the allauth email page explictly
    path('accounts/email/', page_not_found, {'exception': None}),
    path('accounts/', include('allauth.urls')),
    path('ctrl/', admin.site.urls),
    # should only work when debug = True according to doc
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rmn_arch_0/posts/forms.py
from django import forms

from dal.autocomplete import ModelSelect2

from .models import Post, Comment, Report


class StrictNewlineCharField(forms.CharField):
    """
    Strips \r from the value to be compatible with all broswer newline characters
    """
    widget = forms.Textarea
    def to_python(self, value):
        return super().to_python(value).replace('\r', '')


class PostForm(forms.ModelForm):
    """
    Form to create posts
    """
    images = forms.ImageField(widget=forms.FileInput(attrs={'multiple': True}))

    class Meta:
        model = Post
        fields = ['images', 'description', 'anonymous']
        field_classes = {'description': StrictNewlineCharField}


class CommentForm(forms.ModelForm):
    """
    Form to create comments
    """
    class Meta:
        model = Comment
        fields = ['description']
        field_classes = {'description': StrictNewlineCharField}


class ReportForm(forms.ModelForm):
    """
    Form to create reports
    """
    class Meta:
        model = Report
        fields = ['reason', 'description']
        widgets = {'reason': forms.RadioSelect()}
        field_classes = {'description': StrictNewlineCharField}

rmn_arch_0/chat/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views.generic import View, ListView

import json

from .models import Room, Message
from rmn_arch_0.users.models import User


class ChatView(LoginRequiredMixin, ListView):
    """
    Base chat view
        optioanlly accepts a user url param to start new chat or open existing chat
    """
    template_name = 'chat/chat.html'
    context_object_name = 'rooms'

    def get_queryset(self):
        return Room.objects.get_user_rooms(self.request.user)

    def get_context_data(self, tar_user=None, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        if tar_user != None:
            tar_room_name = Room.get_room_name(user, tar_user)
            # if not self.object_list.filter(name=tar_room_name).exists():
            # TODO temp fix, Room.object_list should be a query set
            room_names = [room.name for room in self.object_list]
            if tar_room_name not in room_names:
                context['new_room_name'] = tar_room_name
                context['tar_user'] = tar_user
        for room in self.object_list:
            room.other_user = room.get_other_user_stat(user).user
            if tar_user == room.other_user:
                room.extra_css_class = ' active'
        return context

    def get(self, request, **kwargs):
        tar_user = request.GET.get('user')
        if tar_user != None:
            tar_user = get_object_or_404(User, username=tar_user)
        self.object_list = self.get_queryset()
        context = self.get_context_data(tar_user, **kwargs)
        return render(request, self.template_name, context)


class ChatContentAJAXView(LoginRequiredMixin, ListView):
    """
    Get given chat room content, TODO paginate by timestamp
    """
    template_name = 'chat/chat_content.html'
    context_object_name = 'msgs'

    def get_queryset(self):
        self.room = get_object_or_404(Room, name=self.kwargs['room_name'])
        return self.room.message_set.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['id'] = self.room.name
        return context

rmn_arch_0/core/views.py
from django.shortcuts import render


def terms_and_conditions(request):
    return render(request, 'core/terms_and_conditions.html')

rmn_arch_0/posts/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ValidationError
from django.db.models import Case, When, F, Q, IntegerField
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views.generic import TemplateView, ListView, View
from django.urls import reverse

import json
import random

from .forms import PostForm, CommentForm, ReportForm
from .models import Post, PostImage, Rating, Comment, Report
from rmn_arch_0.users.models import User


class ElPaginatedListView(ListView):
    """
    Endlessly paginated list view
    Requires page_template_name to be set, which would be used for pages after the first
    """
    page_template_name = ''

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_template_name'] = self.page_template_name
        return context

    def get(self, request, **kwargs):
        page_num = request.GET.get('page')
        if page_num == None or page_num == 1:
            return super().get(request, **kwargs)
        else:
            self.object_list = self.get_queryset()
            context = self.get_context_data(**kwargs)
            return render(request, self.page_template_name, context)


class HomeView(ElPaginatedListView):
    """
    Home page
    """
    template_name = 'posts/home.html'
    page_template_name = 'posts/home_posts.html'
    paginate_by = 20
    context_object_name = 'posts'

    def get_queryset(self):
        """
        Returns the posts objects order by newest (-id), annotate the current
        user/session user's ratings if applicable
        """
        q = Q(pk__in=[])    # Django ORM recognises this, always evaluates to False
        if self.request.user.is_authenticated:
            q = Q(rating__user=self.request.user)
        elif self.request.session.session_key:
            q = Q(rating__session_key=self.request.session.session_key)
        return Post.objects.annotate(
            rate = Case(
                When(q, then = F('rating__rate')),
                output_field = IntegerField()
            )
        ).filter(show = True
        ).order_by('-id', 'rate'
        ).distinct('id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # randomly features some images
        last_featured = 0
        for i, post in enumerate(context['posts']):
            if (last_featured + 4 < i and random.random() < 0.5):
                last_featured = i
                post.extra_css_class = ' featured'

        # check whether the user is new
        if not (self.request.user.is_authenticated or self.request.session.session_key):
            self.request.session.create()
            context['first_visit'] = True
        return context


class RankView(TemplateView):
    """
    Page showing weekly/monthly ranings
    """
    template_name = 'posts/rank.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class FollowView(LoginRequiredMixin, ElPaginatedListView):
    """
    Page showing other users that the current user follows
    """
    template_name = 'posts/follow.html'
    page_template_name = 'posts/list_post.html'
    paginate_by = 10
    context_object_name = 'posts'

    def get_queryset(self):
        return Post.objects.filter(
            user__in = self.request.user.relations.follows.all(),
            show = True,
            anonymous=False, #TODO test me
        ).order_by('-id')


class PostCreateModalView(LoginRequiredMixin, TemplateView):
    """
    Page allowing logined user to create new posts
    """
    template_name = 'posts/post_create.html'
    redirect_field_name  = 'ignored' # override default "next" so it redirect to home page

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.method == 'POST':
            context['form'] = PostForm(data=self.request.POST, files=self.request.FILES)
        else:
            context['form'] = PostForm()
        return context

    def post(self, request, **kwargs):
        context = self.get_context_data(**kwargs)
        if context['form'].is_valid():
            post = context['form'].save(commit=False)
            post.user = request.user
            post.save()
            for file in request.FILES.getlist('images'):
                PostImage.objects.create(post=post, image=file)

            messages.success(request, 'You have created a new post')
            return HttpResponseRedirect(reverse('posts:home'))
        return self.render_to_response(context)


class PostDetailModalView(ElPaginatedListView):
    """
    Display indiviudal post as a modal content
    note this is subclass ListView (instead of DetailView) to facilitate pagniating comments
    """
    template_name = 'posts/post_detail_post.html'
    page_template_name = 'posts/post_detail_comments.html'
    paginate_by = 10
    context_object_name = 'comments'

    def get_object(self):
        """
        Return the actual Post object
        """
        return get_object_or_404(Post, uuid=self.kwargs['uuid'], show=True)

    def get_queryset(self):
        """
        Return the comments related to the given post
        """
        self.object = self.get_object()
        return Comment.objects.filter(post=self.object).order_by('id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post'] = self.object
        # get current user/session user's rating
        rating = None
        if self.request.user.is_authenticated:
            rating = Rating.objects.filter(
                    user=self.request.user, post=self.object
                ).first()
        elif self.request.session.session_key:
            rating = Rating.objects.filter(
                    session_key=self.request.session.session_key, post=self.object
                ).first()
        context['rate'] = rating.rate if rating else None

        context['comment_form'] = CommentForm(prefix='comment')
        context['report_form'] = ReportForm(prefix='report')
        return context


class PostDetailView(PostDetailModalView):
    """
    Display individual post as a page
    """
    template_name = 'posts/post_detail.html'


class PostCommentAJAXView(LoginRequiredMixin, View):
    """
    Accepts AJAX request for new comment for logined user
    Returns comment_snippet of the new comment when successful, HTTP 400 otherwise
    """
    def post(self, request, **kwargs):
        post = Post.objects.get(uuid=self.kwargs['uuid'])
        comment_form = CommentForm(data=self.request.POST, prefix='comment')
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.user = request.user
            comment.save()
            return render(request,
                'posts/snippets/comment_snippet.html',
                {'comment': comment, 'fade': True})
        return HttpResponse(status=400)


class PostReportAJAXView(LoginRequiredMixin, PostDetailModalView):
    """
    Accepts AJAX request for new reports for logined user
    Returns HTTP 200 when successful, HTTP 400 otherwise
    """
    def post(self, request, **kwargs):
        post = Post.objects.get(uuid=self.kwargs['uuid'])
        report, _ = Report.objects.get_or_create(user=request.user, post=post)
        report_form = ReportForm(data=self.request.POST, instance=report, prefix='report')
        if report_form.is_valid():
            report_form.save()
            return HttpResponse(status=200)
        return HttpResponse(status=400)


class PostRateAJAXView(View):
    """
    Endpoint allowing site visiter to rate a post
    Only accepts POST requests, requires
        uuid    string, uuid of the post
        rate    integer, desired rates
    returns HTTP 404 if not found
        HTTP 400 bad request
        HTTP 200 otherwise
    """
    def post(self, request):
        payload = json.loads(request.body)
        uuid = payload.get('uuid', None)
        rate = payload.get('rate', None)
        if (uuid == None or rate == None):
            return HttpResponse(status=400)
        post = get_object_or_404(Post, uuid=uuid)
        try:
            if request.user.is_authenticated:
                Rating.objects.update_or_create(
                    user=request.user,
                    post=post,
                    defaults={
                        'rate': rate,
                    })
            else:
                if not request.session.session_key:
                    request.session.create()
                Rating.objects.update_or_create(
                    session_key=request.session.session_key,
                    post=post,
                    defaults={
                        'rate': rate,
                    })
        except ValidationError:
            return HttpResponse(status=400)
        return HttpResponse(status=200)


class UserPostsView(ElPaginatedListView):
    """
    Display post made by a specific user
    """
    template_name = 'posts/user_posts.html'
    page_template_name = 'posts/list_post.html'
    paginate_by = 10
    context_object_name = 'posts'

    def get_queryset(self):
        user = User.objects.get(username=self.kwargs['username'])
        self.user = user
        return Post.objects.filter(user=user, anonymous=False, show=True).order_by('-id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['curr_user'] = self.user
        return context

rmn_arch_0/templates/posts/follow.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Follow - {{ block.super }}{% endblock title %}
{% block metatags %}
<meta name="robots" content="noindex">
{% endblock metatags %}

{% block js %}
{{ block.super }}
<script type="module">
    import { Paginator } from "{% static 'js/pagination.js' %}";
    import { get_post } from "{% static 'js/get_post.js' %}";

    const comment_paginator = new Paginator('{{ request.path }}');

    // open existing post
    document.addEventListener(
        'click',
        (event) => { get_post(event); },
        false,
    );
</script>
{% endblock js %}

{% block content %}
<main class="centered">
    <div class="post-list-container">
        {% include page_template_name %}
        {% if not posts %}
        <h2 class="centered">You haven't follow anyone yet!</h2>
        {% endif %}
    </div>
</main>
{% endblock %}

rmn_arch_0/templates/posts/home_posts.html
{% for post in posts %}
<a href="{{ post.get_absolute_url }}" class="deco-none grid-item post{{ post.extra_css_class }}"
    style="background-image: url('{{ post.thumbnail_image_url }}');" data-uuid="{{ post.uuid }}">
    <div class="grid-content">
        {% include 'posts/snippets/rating_snippet.html' with rate=post.rate %}
    </div>
</a>
{% endfor %}

{{ page_obj.has_next|json_script:'paginate_hook' }}

rmn_arch_0/templates/posts/list_post.html
{% for post in posts %}
<div class="post-list-div">
    <img src="{{ post.user_display_image_url }}" alt="Poster Profile Image"
        class="img-circle m-profile-img">
    <div class="post-list-content">
        <strong>{{ post.user_display_name }}</strong>
        {% if post.description %}
        <span>{{ post.description }}</span>
        {% endif %}
        <div class="grid">
            {% for image in post.postimage_set.all %}
            <a href="{{ post.get_absolute_url }}" class="deco-none grid-item post"
                style="background-image: url('{{ image.image.url }}');" data-uuid="{{ post.uuid }}">
            </a>
            {% endfor %}
        </div>
    </div>
</div>
{% endfor %}

{{ page_obj.has_next|json_script:'paginate_hook' }}

rmn_arch_0/templates/posts/post_create.html
{% load static %}
{% load crispy_forms_tags %}

<script type="module">
    import { check_textarea_length } from "{% static 'js/form_validation.js' %}";
    import { ImageCompressionInput } from "{% static 'js/image_compression_input.js' %}";

    document.getElementById('id_description').addEventListener('input', (event) => {
        check_textarea_length(event);
    }, false);
    new ImageCompressionInput('id_images', 'img_preview', 9);
</script>

<div class="post-create-div">
    <div class="preview-imgs">
        <img src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7"
            alt="Image Prevew" id="img_preview0">
        <img src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7"
            alt="Image Prevew" id="img_preview1">
        <img src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7"
            alt="Image Prevew" id="img_preview2">
        <img src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7"
            alt="Image Prevew" id="img_preview3">
        <img src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7"
            alt="Image Prevew" id="img_preview4">
        <img src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7"
            alt="Image Prevew" id="img_preview5">
        <img src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7"
            alt="Image Prevew" id="img_preview6">
        <img src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7"
            alt="Image Prevew" id="img_preview7">
        <img src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7"
            alt="Image Prevew" id="img_preview8">
    </div>
    <form id="post_form" method="post" action="{% url 'posts:post_create_modal' %}"
        enctype="multipart/form-data" style="height: unset;">
        <h1>Create New Post</h1>
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn-primary" type="submit">Create</button>
    </form>
</div>

rmn_arch_0/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Post by {{ post.user_display_name }} - {{ block.super }}{% endblock title %}

{% block js %}
{{ block.super }}
<script type="module">
    import { rate } from "{% static 'js/rate.js' %}";

    document.addEventListener(
        'click',
        async (event) => { rate(event); },
        false
    );
</script>
{% endblock js %}

{% block content %}
<main class="centered">
    <div class="card">
        {% include 'posts/post_detail_post.html' %}
    </div>
</main>
{% endblock %}

rmn_arch_0/templates/posts/post_detail_comments.html
{% for comment in comments %}
{% include 'posts/snippets/comment_snippet.html' %}
{% endfor %}

{{ page_obj.has_next|json_script:'comment_paginate_hook' }}

rmn_arch_0/templates/posts/post_detail_post.html
{% load static %}
{% load crispy_forms_tags %}

<script type="module">
    import { Carousel } from "{% static 'js/carousel.js' %}";
    import { check_textarea_length } from "{% static 'js/form_validation.js' %}";
    import { Paginator } from "{% static 'js/pagination.js' %}";
    import { follow } from "{% static 'js/follow.js' %}";

    new Carousel();
    const comment_paginator = new Paginator(
        '{{ request.path }}',
        50,
        document.querySelector('.post-comments'),
        'comment_paginate_hook',
    );

    // add validator to textarea
    document.querySelectorAll('textarea').forEach((elem) => {
        elem.addEventListener('input', (event) => {
            check_textarea_length(event);
        }, false);
    });

    // handles comment submit
    document.getElementById('comment_form').addEventListener(
        'submit',
        async (event) => {
            event.preventDefault();
            event.target.querySelector('button').disabled = true;
            const data = new FormData(event.target);
            const res = await fetch("{% url 'posts:post_comment' post.uuid %}", {
                method: 'POST',
                body: data,
            });
            if (!res.ok) {
                event.target.innerHTML = 'Network error, please try again later';
            } else {
                // show the comment rightaway if able
                if (!comment_paginator.more) {
                    // remove the cta if exists
                    const comment_cta = document.getElementById('comment_cta');
                    if (comment_cta) {
                        comment_cta.remove();
                    }

                    const content = document.createElement('div');
                    content.innerHTML = await res.text();
                    const paginate_hook = document.getElementById('comment_paginate_hook');
                    paginate_hook.before(content);
                    content.replaceWith(...content.childNodes);
                    comment_paginator.scorll_obj.scrollTop = comment_paginator.scorll_obj.scrollHeight;
                }

                // reset the form content
                event.target.reset();
                document.getElementById('id_comment-description').dispatchEvent(
                    new Event('input', { bubbles: true }));
                event.target.querySelector('button').disabled = false;
            }
        },
        false
    );

    // handle report
    document.getElementById('id_report_icon').addEventListener(
        'click',
        (event) => {
            event.target.classList.toggle('active');
            document.querySelector('.post-comments').classList.toggle('dsp-none');
            document.querySelector('.post-comment-form').classList.toggle('dsp-none');
            document.querySelector('.post-report-form').classList.toggle('dsp-none');
        },
        false);
    document.getElementById('report_form').addEventListener(
        'submit',
        async (event) => {
            event.preventDefault();
            event.target.querySelector('button').disabled = true;
            const data = new FormData(event.target);
            const res = await fetch("{% url 'posts:post_report' post.uuid %}", {
                method: 'POST',
                body: data,
            });
            if (!res.ok) {
                event.target.innerHTML = 'Network error, please try again later';
            } else {
                event.target.innerHTML = 'Your report has been submitted!'
            }
        },
        false
    );

    // handle follow
    const follow_icon = document.getElementById('id_follow_icon_post');
    if (follow_icon) {
        follow_icon.addEventListener(
            'click',
            (event) => { follow(event); },
            false,
        );
    }
</script>

<div class="post-detail-div">
    <div class="carousel-div">
        <div class="carousel">
            {% for img in post.postimage_set.all %}
            <img class="carousel-cell fade" src="{{ img.image.url }}" alt="Post Image">
            {% endfor %}
            <a class="prev">
                <span>&#10094;</span>
            </a>
            <a class="next">
                <span>&#10095;</span>
            </a>
        </div>
        <div class="carousel-dots">
            {% for img in post.postimage_set.all %}
            <span class="dot" data-index="{{ forloop.counter0 }}"></span>
            {% endfor %}
        </div>
    </div>

    <div class="post-sidebar" data-uuid="{{ post.uuid }}">
        <div class="post-user">
            <img src="{{ post.user_display_image_url }}" alt="Poster Profile Image"
                class="img-circle m-profile-img">
            <div class="post-user-info">
                <a {% if not post.anonymous %}href="{{ post.user.get_absolute_url }}" {% endif %}>
                    <strong>{{ post.user_display_name }}</strong>
                </a>
                {% if not post.anonymous and post.user.profile.location %}
                <div class="post-user-location">{{ post.user.profile.location }}</div>
                {% endif %}
            </div>
            {% if user.is_authenticated and not post.anonymous and user != post.user %}
            <a href="{% url 'chat:messages' %}?user={{ post.user.username }}" class="icon post-icon" id="id_chat_icon_post"></a>
            <div class="icon post-icon follow-icon{% if post.user in user.relations.follows.all %} active{% endif %}"
                id="id_follow_icon_post" data-username="{{ post.user.username }}"></div>
            {% endif %}
        </div>
        <div class="post-comments">
            {% if post.description %}
            {% include 'posts/snippets/comment_snippet.html' with comment=post %}
            {% endif %}
            {% if post.comment_set.count == 0 %}
            <div class="comment" id="comment_cta">
                Be the first to comment this post!
            </div>
            {% endif %}
            {% include page_template_name %}
        </div>
        <div class="post-reactions">
            {% include 'posts/snippets/rating_snippet.html' %}
            <div class="list-icons">
                <div class="icon post-extra-icon" id="id_report_icon"></div>
            </div>
            <div class="post-ratings">
                {% if post.rating_summary.image %}
                <img class="img-circle" src="{{ post.rating_summary.image }}"
                    alt="Rater Profile Image">
                <span>
                    Rated by <strong>{{ post.rating_summary.name }}</strong> and
                    {{ post.rating_count }} others
                </span>
                {% else %}
                <span>
                    Be the first to rate this post!
                </span>
                {% endif %}
            </div>
            {% if post.rating_count >= post.MIN_RATINGS_TO_SHOW %}
            <div class="post-avg-rating fade{% if rate %} rated{% endif %}">
                with an average rating of {{ post.avg_rate|floatformat }}
            </div>
            {% endif %}
        </div>
        <form id="comment_form" class="post-comment-form">
            {% if user.is_authenticated %}
            {% csrf_token %}
            <div>
                <div>{{ comment_form.description }}</div>
            </div>
            <button class="btn-secondary">Comment</button>
            {% else %}
            <span>Please
                <a href="{% url 'account_login' %}?next={% url 'posts:post_detail' post.uuid %}">
                    sign in
                </a>
                to comment
            </span>
            {% endif %}
        </form>
        <form id="report_form" class="post-report-form dsp-none">
            {% if user.is_authenticated %}
            {% csrf_token %}
            {{ report_form|crispy }}
            <button class="btn-secondary">Report</button>
            {% else %}
            <span>Please
                <a href="{% url 'account_login' %}?next={% url 'posts:post_detail' post.uuid %}">
                    sign in
                </a>
                to report
            </span>
            {% endif %}
        </form>
    </div>
</div>

rmn_arch_0/templates/posts/rank.html
{% extends 'base.html' %}

{% block title %}Rank - {{ block.super }}{% endblock title %}
{% block metatags %}
<meta name="robots" content="noindex"><!-- TODO remove -->
{% endblock metatags %}

{% block content %}
<main class="centered">
    <h1>Coming Soon!</h1>
</main>
{% endblock %}

rmn_arch_0/templates/posts/user_posts.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Posts by {{ curr_user.name }} - {{ block.super }}{% endblock title %}

{% block js %}
{{ block.super }}
<script type="module">
    import { Paginator } from "{% static 'js/pagination.js' %}";
    import { follow } from "{% static 'js/follow.js' %}";
    import { get_post } from "{% static 'js/get_post.js' %}";

    const comment_paginator = new Paginator('{{ request.path }}');

    // handle follow
    const follow_icon = document.getElementById('id_follow_icon_user');
    if (follow_icon) {
        follow_icon.addEventListener(
            'click',
            (event) => { follow(event); },
            false,
        );
    }

    // open existing post
    document.addEventListener(
        'click',
        (event) => { get_post(event); },
        false,
    );
</script>
{% endblock js %}

{% block content %}
<main class="centered">
    <div class="users-posts-profile">
        <div class="user-posts-user">
            <img src="{{ curr_user.profile_image_url }}" alt="User Profile Image"
                class="img-circle user-post-img">
            <div class="profile-div">
                <span>{{ curr_user.name }}</span>
                <a>@{{ curr_user.username }}</a>
            </div>
        </div>
        {% if user.is_authenticated and user != curr_user %}
        <div class="list-icons">
            <a href="{% url 'chat:messages' %}?user={{ curr_user.username }}" class="icon user-icon" id="id_chat_icon_user"></a>
            <div class="icon user-icon follow-icon{% if curr_user in user.relations.follows.all %} active{% endif %}"
                id="id_follow_icon_user" data-username="{{ curr_user.username }}"></div>
        </div>
        {% endif %}
    </div>
    <div class="users-posts-follow-block">
        <span>{{ curr_user.pub_post_count }} posts</span>
        <span>{{ curr_user.follower_count }} followers</span>
        <span>{{ curr_user.following_count }} following</span>
    </div>
    <div class="post-list-container">
        {% include page_template_name %}
        {% if not posts %}
        <h2 class="centered">{{ curr_user.name }} has no posts yet!</h2>
        {% endif %}
    </div>
</main>
{% endblock %}