rmn_arch_0/chat/urls.py
from django.urls import path
from .views import (
    ChatView,
    ChatContentAJAXView,
)

app_name = 'chat'

urlpatterns = [
    path('', ChatView.as_view(), name='messages'),
    path('chat-content/<str:room_name>/', ChatContentAJAXView.as_view(), name='chat_content'),
]

rmn_arch_0/core/urls.py
from django.urls import path
from .views import terms_and_conditions

app_name = 'core'

urlpatterns = [
    path('terms-and-conditions/', terms_and_conditions, name='terms_and_conditions'),
]

rmn_arch_0/posts/urls.py
from django.urls import path
from .views import (
    HomeView,
    RankView,
    FollowView,
    PostCreateModalView,
    PostDetailModalView,
    PostDetailView,
    PostCommentAJAXView,
    PostReportAJAXView,
    PostRateAJAXView,
    UserPostsView,
)

app_name = 'posts'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('rank/', RankView.as_view(), name='rank'),
    path('follow/', FollowView.as_view(), name='follow'),
    path('posts/create/m/', PostCreateModalView.as_view(), name='post_create_modal'),
    path('posts/<uuid:uuid>/m/', PostDetailModalView.as_view(), name='post_detail_modal'),
    path('posts/<uuid:uuid>/', PostDetailView.as_view(), name='post_detail'),
    path('posts/<uuid:uuid>/comment/', PostCommentAJAXView.as_view(), name='post_comment'),
    path('posts/<uuid:uuid>/report/', PostReportAJAXView.as_view(), name='post_report'),
    path('posts/rate/', PostRateAJAXView.as_view(), name='rate'),
    path('users/<str:username>/posts/', UserPostsView.as_view(), name='user_posts'),
]

rmn_arch_0/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.views.defaults import page_not_found
from django.urls import path, include


urlpatterns = [
    path('', include('rmn_arch_0.core.urls')),
    path('', include('rmn_arch_0.posts.urls')),
    path('messages/', include('rmn_arch_0.chat.urls')),
    path('users/', include('rmn_arch_0.users.urls')),
    # block the allauth email page explictly
    path('accounts/email/', page_not_found, {'exception': None}),
    path('accounts/', include('allauth.urls')),
    path('ctrl/', admin.site.urls),
    # should only work when debug = True according to doc
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rmn_arch_0/users/urls.py
from django.urls import path
from .views import (
    UsernameCheckAJAXView,
    CityAutocompleteView,
    ProfileEditView,
    SettingsView,
    UserFollowAJAXView,
)

app_name = 'users'

urlpatterns = [
    path('username-check/', UsernameCheckAJAXView.as_view(), name='username_check'),
    path('dal-city/', CityAutocompleteView.as_view(), name='city_autocomplete'),
    path('profile/edit/', ProfileEditView.as_view(), name='profile_edit'),
    path('settings/', SettingsView.as_view(), name='settings'),
    path('follow/', UserFollowAJAXView.as_view(), name='follow'),
]

rmn_arch_0/posts/forms.py
from django import forms

from dal.autocomplete import ModelSelect2

from .models import Post, Comment, Report


class StrictNewlineCharField(forms.CharField):
    """
    Strips \r from the value to be compatible with all broswer newline characters
    """
    widget = forms.Textarea
    def to_python(self, value):
        return super().to_python(value).replace('\r', '')


class PostForm(forms.ModelForm):
    """
    Form to create posts
    """
    images = forms.ImageField(widget=forms.FileInput(attrs={'multiple': True}))

    class Meta:
        model = Post
        fields = ['images', 'description', 'anonymous']
        field_classes = {'description': StrictNewlineCharField}


class CommentForm(forms.ModelForm):
    """
    Form to create comments
    """
    class Meta:
        model = Comment
        fields = ['description']
        field_classes = {'description': StrictNewlineCharField}


class ReportForm(forms.ModelForm):
    """
    Form to create reports
    """
    class Meta:
        model = Report
        fields = ['reason', 'description']
        widgets = {'reason': forms.RadioSelect()}
        field_classes = {'description': StrictNewlineCharField}

rmn_arch_0/chat/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views.generic import View, ListView

import json

from .models import Room, Message
from rmn_arch_0.users.models import User


class ChatView(LoginRequiredMixin, ListView):
    """
    Base chat view
        optioanlly accepts a user url param to start new chat or open existing chat
    """
    template_name = 'chat/chat.html'
    context_object_name = 'rooms'

    def get_queryset(self):
        return Room.objects.get_user_rooms(self.request.user)

    def get_context_data(self, tar_user=None, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        if tar_user != None:
            tar_room_name = Room.get_room_name(user, tar_user)
            # if not self.object_list.filter(name=tar_room_name).exists():
            # TODO temp fix, Room.object_list should be a query set
            room_names = [room.name for room in self.object_list]
            if tar_room_name not in room_names:
                context['new_room_name'] = tar_room_name
                context['tar_user'] = tar_user
        for room in self.object_list:
            room.other_user = room.get_other_user_stat(user).user
            if tar_user == room.other_user:
                room.extra_css_class = ' active'
        return context

    def get(self, request, **kwargs):
        tar_user = request.GET.get('user')
        if tar_user != None:
            tar_user = get_object_or_404(User, username=tar_user)
        self.object_list = self.get_queryset()
        context = self.get_context_data(tar_user, **kwargs)
        return render(request, self.template_name, context)


class ChatContentAJAXView(LoginRequiredMixin, ListView):
    """
    Get given chat room content, TODO paginate by timestamp
    """
    template_name = 'chat/chat_content.html'
    context_object_name = 'msgs'

    def get_queryset(self):
        self.room = get_object_or_404(Room, name=self.kwargs['room_name'])
        return self.room.message_set.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['id'] = self.room.name
        return context

rmn_arch_0/core/views.py
from django.shortcuts import render


def terms_and_conditions(request):
    return render(request, 'core/terms_and_conditions.html')

rmn_arch_0/posts/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ValidationError
from django.db.models import Case, When, F, Q, IntegerField
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views.generic import TemplateView, ListView, View
from django.urls import reverse

import json
import random

from .forms import PostForm, CommentForm, ReportForm
from .models import Post, PostImage, Rating, Comment, Report
from rmn_arch_0.users.models import User


class ElPaginatedListView(ListView):
    """
    Endlessly paginated list view
    Requires page_template_name to be set, which would be used for pages after the first
    """
    page_template_name = ''

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_template_name'] = self.page_template_name
        return context

    def get(self, request, **kwargs):
        page_num = request.GET.get('page')
        if page_num == None or page_num == 1:
            return super().get(request, **kwargs)
        else:
            self.object_list = self.get_queryset()
            context = self.get_context_data(**kwargs)
            return render(request, self.page_template_name, context)


class HomeView(ElPaginatedListView):
    """
    Home page
    """
    template_name = 'posts/home.html'
    page_template_name = 'posts/home_posts.html'
    paginate_by = 20
    context_object_name = 'posts'

    def get_queryset(self):
        """
        Returns the posts objects order by newest (-id), annotate the current
        user/session user's ratings if applicable
        """
        q = Q(pk__in=[])    # Django ORM recognises this, always evaluates to False
        if self.request.user.is_authenticated:
            q = Q(rating__user=self.request.user)
        elif self.request.session.session_key:
            q = Q(rating__session_key=self.request.session.session_key)
        return Post.objects.annotate(
            rate = Case(
                When(q, then = F('rating__rate')),
                output_field = IntegerField()
            )
        ).filter(show = True
        ).order_by('-id', 'rate'
        ).distinct('id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # randomly features some images
        last_featured = 0
        for i, post in enumerate(context['posts']):
            if (last_featured + 4 < i and random.random() < 0.5):
                last_featured = i
                post.extra_css_class = ' featured'

        # check whether the user is new
        if not (self.request.user.is_authenticated or self.request.session.session_key):
            self.request.session.create()
            context['first_visit'] = True
        return context


class RankView(TemplateView):
    """
    Page showing weekly/monthly ranings
    """
    template_name = 'posts/rank.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class FollowView(LoginRequiredMixin, ElPaginatedListView):
    """
    Page showing other users that the current user follows
    """
    template_name = 'posts/follow.html'
    page_template_name = 'posts/list_post.html'
    paginate_by = 10
    context_object_name = 'posts'

    def get_queryset(self):
        return Post.objects.filter(
            user__in = self.request.user.relations.follows.all(),
            show = True,
            anonymous=False, #TODO test me
        ).order_by('-id')


class PostCreateModalView(LoginRequiredMixin, TemplateView):
    """
    Page allowing logined user to create new posts
    """
    template_name = 'posts/post_create.html'
    redirect_field_name  = 'ignored' # override default "next" so it redirect to home page

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.method == 'POST':
            context['form'] = PostForm(data=self.request.POST, files=self.request.FILES)
        else:
            context['form'] = PostForm()
        return context

    def post(self, request, **kwargs):
        context = self.get_context_data(**kwargs)
        if context['form'].is_valid():
            post = context['form'].save(commit=False)
            post.user = request.user
            post.save()
            for file in request.FILES.getlist('images'):
                PostImage.objects.create(post=post, image=file)

            messages.success(request, 'You have created a new post')
            return HttpResponseRedirect(reverse('posts:home'))
        return self.render_to_response(context)


class PostDetailModalView(ElPaginatedListView):
    """
    Display indiviudal post as a modal content
    note this is subclass ListView (instead of DetailView) to facilitate pagniating comments
    """
    template_name = 'posts/post_detail_post.html'
    page_template_name = 'posts/post_detail_comments.html'
    paginate_by = 10
    context_object_name = 'comments'

    def get_object(self):
        """
        Return the actual Post object
        """
        return get_object_or_404(Post, uuid=self.kwargs['uuid'], show=True)

    def get_queryset(self):
        """
        Return the comments related to the given post
        """
        self.object = self.get_object()
        return Comment.objects.filter(post=self.object).order_by('id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post'] = self.object
        # get current user/session user's rating
        rating = None
        if self.request.user.is_authenticated:
            rating = Rating.objects.filter(
                    user=self.request.user, post=self.object
                ).first()
        elif self.request.session.session_key:
            rating = Rating.objects.filter(
                    session_key=self.request.session.session_key, post=self.object
                ).first()
        context['rate'] = rating.rate if rating else None

        context['comment_form'] = CommentForm(prefix='comment')
        context['report_form'] = ReportForm(prefix='report')
        return context


class PostDetailView(PostDetailModalView):
    """
    Display individual post as a page
    """
    template_name = 'posts/post_detail.html'


class PostCommentAJAXView(LoginRequiredMixin, View):
    """
    Accepts AJAX request for new comment for logined user
    Returns comment_snippet of the new comment when successful, HTTP 400 otherwise
    """
    def post(self, request, **kwargs):
        post = Post.objects.get(uuid=self.kwargs['uuid'])
        comment_form = CommentForm(data=self.request.POST, prefix='comment')
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.user = request.user
            comment.save()
            return render(request,
                'posts/snippets/comment_snippet.html',
                {'comment': comment, 'fade': True})
        return HttpResponse(status=400)


class PostReportAJAXView(LoginRequiredMixin, PostDetailModalView):
    """
    Accepts AJAX request for new reports for logined user
    Returns HTTP 200 when successful, HTTP 400 otherwise
    """
    def post(self, request, **kwargs):
        post = Post.objects.get(uuid=self.kwargs['uuid'])
        report, _ = Report.objects.get_or_create(user=request.user, post=post)
        report_form = ReportForm(data=self.request.POST, instance=report, prefix='report')
        if report_form.is_valid():
            report_form.save()
            return HttpResponse(status=200)
        return HttpResponse(status=400)


class PostRateAJAXView(View):
    """
    Endpoint allowing site visiter to rate a post
    Only accepts POST requests, requires
        uuid    string, uuid of the post
        rate    integer, desired rates
    returns HTTP 404 if not found
        HTTP 400 bad request
        HTTP 200 otherwise
    """
    def post(self, request):
        payload = json.loads(request.body)
        uuid = payload.get('uuid', None)
        rate = payload.get('rate', None)
        if (uuid == None or rate == None):
            return HttpResponse(status=400)
        post = get_object_or_404(Post, uuid=uuid)
        try:
            if request.user.is_authenticated:
                Rating.objects.update_or_create(
                    user=request.user,
                    post=post,
                    defaults={
                        'rate': rate,
                    })
            else:
                if not request.session.session_key:
                    request.session.create()
                Rating.objects.update_or_create(
                    session_key=request.session.session_key,
                    post=post,
                    defaults={
                        'rate': rate,
                    })
        except ValidationError:
            return HttpResponse(status=400)
        return HttpResponse(status=200)


class UserPostsView(ElPaginatedListView):
    """
    Display post made by a specific user
    """
    template_name = 'posts/user_posts.html'
    page_template_name = 'posts/list_post.html'
    paginate_by = 10
    context_object_name = 'posts'

    def get_queryset(self):
        user = User.objects.get(username=self.kwargs['username'])
        self.user = user
        return Post.objects.filter(user=user, anonymous=False, show=True).order_by('-id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['curr_user'] = self.user
        return context

rmn_arch_0/templates/base.html
{% load static %}
{% load chat_tags %}

<!DOCTYPE html>
<html lang="en" tabindex="0">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}rmn_arch_0{% endblock title %}</title>
    <meta name="description"
        content="rmn_arch_0 is the best free and safe nudity sharing community for all your needs! Join today to post your pictures!">
    {% block metatags %}
    {% endblock metatags %}

    {% block js %}
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-PYH0K31WNG"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'G-PYH0K31WNG');
    </script>

    <script type="module">
        import { get_cookie } from "{% static 'js/get_cookie.js' %}";

        // store django urls and other related data
        window.dj_data = {
            csfr_token: get_cookie('csrftoken'),
            url_key: 'd641092d-eeb3-414f-bfa5-a208b1f628e2',
            urls: {
                chat: {
                    messages: "{% url 'chat:messages' %}",
                    chat_content: "{% url 'chat:chat_content' 'd641092d-eeb3-414f-bfa5-a208b1f628e2' %}",
                },
                posts: {
                    post_create_modal: "{% url 'posts:post_create_modal' %}",
                    post_detail_modal: "{% url 'posts:post_detail_modal' 'd641092d-eeb3-414f-bfa5-a208b1f628e2' %}",
                    rate: "{% url 'posts:rate' %}",
                },
                users: {
                    username_check: "{% url 'users:username_check' %}",
                    follow: "{% url 'users:follow' %}",
                },
            },
        }

        // hide messages
        let pops = document.getElementById('pop-ups').children;
        setTimeout((elem) => {
            for (let elem of pops) {
                elem.classList.add('removed');
            }
        }, 4000);
    </script>
    {% endblock %}
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon/favicon.ico' %}" />
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'favicon/site.webmanifest' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
    <nav>
        <div class="navbar">
            <a href="{% url 'posts:home' %}">
                <img class="logo" src="{% static 'images/logo.png' %}" alt="rmn_arch_0 Logo">
            </a>
            <div class="nav-group-div">
                <img class="icon nav-menu-btn" src="{% static 'images/menu.svg' %}" alt="Menu Icon"
                    tabindex="1">
                {% with url_name=request.resolver_match.url_name %}
                <ul class="list-icons nav-group">
                    <li>
                        <a href="{% url 'posts:home' %}">
                            <div class="icon nav-icon{% if url_name == 'home' %} active{% endif %}"
                                id="id_home_icon"></div>
                            <span>Home</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'posts:rank' %}">
                            <div class="icon nav-icon{% if url_name == 'rank' %} active{% endif %}"
                                id="id_rank_icon"></div>
                            <span>Rank</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'posts:follow' %}">
                            <div class="icon nav-icon{% if url_name == 'follow' %} active{% endif %}"
                                id="id_follow_icon"></div>
                            <span>Follow</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'chat:messages' %}">
                            <div class="icon nav-icon{% chat_extra_css url_name user %}"
                                id="id_chat_icon"></div>
                            <span>Messages</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'users:profile_edit' %}">
                            <img class="icon img-circle{% if url_name == 'profile_edit' %} active{% endif %}"
                                src="{% if user.is_authenticated %}{{ user.profile_image_url }}{% else %}{% static 'images/default_profile_img.png' %}{% endif %}"
                                alt="Profile Image" id="profile_image">
                            <span>Profile</span>
                        </a>
                    </li>
                </ul>
                {% endwith %}
            </div>
        </div>
    </nav>
    <div id="pop-ups">
        {% if messages %}
        {% for message in messages %}
        <div>
            {{message.level_tag}}: {{message}}
        </div>
        {% endfor %}
        {% endif %}
    </div>
    <div class="modal">
        <span class="close">&times;</span>
        <div class="modal-content">
        </div>
    </div>

    {% block content %}
    {% endblock %}

    {% csrf_token %}
</body>

</html>